# Generated by Django 4.2.6 on 2025-10-24 10:00

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_report_data_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=api.models.generate_share_token,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="api.report",
                    ),
                ),
            ],
            options={
                "db_table": "api_sharedreport",
            },
        ),
    ]
