# Generated by Django 4.2.6 on 2025-10-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_sharedreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedreport",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="share_links",
                to="api.report",
            ),
        ),
    ]
